# Generated by Django 4.2.5 on 2023-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesFilms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_creation',
            field=models.DateField(),
        ),
    ]
