# Generated by Django 4.2.5 on 2023-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesFilms', '0003_realisateur_alter_film_realisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('film', models.ManyToManyField(to='lesFilms.film')),
            ],
        ),
    ]
