# Generated by Django 4.2.5 on 2023-10-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesFilms', '0004_acteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acteur',
            name='role',
        ),
    ]
