# Generated by Django 4.2.5 on 2023-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesFilms', '0005_remove_acteur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acteur',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='acteurs',
            field=models.ManyToManyField(related_name='films', to='lesFilms.acteur'),
        ),
    ]
